import { Button } from './components/ui/button'
import {Github, Linkedin, FileVideo, Upload, Wand2 } from 'lucide-react' 
import { Separator } from './components/ui/separator'
import { Textarea } from './components/ui/textarea'
import { Label } from './components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './components/ui/select'
import { Slider } from './components/ui/slider'
export function App() {


  return (
    <div className='min-h-screen flex flex-col'>
      <div className='px-6 py-3 flex items-center justify-between border-b'>
        <h1 className='text-xl font-bold'>upload.ai</h1>
        <div className='flex items-center gap-3'>
          <Button variant="secondary" className='rounded-[0.5rem]'>
            <Linkedin className='w-4 h-4 mr-2'/>
            Linkedin
          </Button>
          <Separator orientation='vertical' className='h-6'/>
          <Button variant="secondary" className='rounded-[0.5rem]'>
            <Github className='w-4 h-4 mr-2'/>  
            Github
          </Button>
        </div>
      </div>
      <main className='flex-1 p-6 flex gap-6'>
        <div className='flex flex-col flex-1 gap-4'>
          <div className='grid grid-rows-2 gap-4 flex-1'>
            <Textarea
              className='resize-none p-5 leading-relaxed'
              placeholder='Include the prompt for the AI...'
            />
            <Textarea
              className='resize-none p-5 leading-relaxed'
              placeholder='Output generated by AI...' 
              readOnly
            />
          </div>
          <p className='text-sm text-muted-foreground'>
          <code className='text-primary'>Remember:</code> you can use the <code className='font-bold'>{`{transcription}`}</code> variable
          in your prompt to add the content of
          the selected video's transcription
          </p>
        </div>

        <aside className='w-80 space-y-6'>
          <form className='space-y-6'>
            <label 
              htmlFor="video"
              className='border flex rounded-md aspect-video cursor-pointer border-dashed text-sm flex-col gap-2 items-center justify-center text-muted-foreground hover:bg-primary/5'
            >
              <FileVideo className='w-6 h-6 '/>
              Video
            </label>
            <input type="file" id='video' accept='video/mp4' className='sr-only'/>
            <Separator/>
            <div className='space-y-2'>
              <Label htmlFor='transcription_prompt'>Transition prompt</Label>
              <Textarea 
                id='transcription_prompt' 
                className='h-20 leading-relaxed resize-none' 
                placeholder='Include keywords mentioned in the video, separated by commas ( , )'
              />
            </div>
            <Button className='rounded-[0.5rem] w-full' type='submit'>
              Upload video
              <Upload className='w-4 h-4 ml-2'/>
            </Button>
          </form>

          <Separator/>

          <form className='space-y-6'>
          <div className='space-y-2'>
              <Label>Prompt</Label>
              <Select >
                <SelectTrigger>
                  <SelectValue placeholder='Select a prompt'/>
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="title">Youtube Title</SelectItem>
                  <SelectItem value="description">Youtube Description</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className='space-y-2'>
              <Label>Model</Label>
              <Select defaultValue='gpt3.5' disabled>
                <SelectTrigger>
                  <SelectValue/>
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="gpt3.5">GPT 3.5-turbo 16k</SelectItem>
                </SelectContent>
              </Select>
              <span className='block text-xs text-muted-foreground italic leading-relaxed'>
                It will be possible to customize this option soon.
              </span>
            </div>

            <Separator/>

            <div className='space-y-4'>
              <Label>Temperature</Label>
              <Slider
                min={0}
                max={1}
                step={0.1}
              />
              <span className='block text-xs text-muted-foreground italic leading-relaxed'>
                Higher values tend to make the results more creative and potentially prone to errors.
              </span>

              <Separator/>
              
              <Button type='submit' className='w-full rounded-[0.5rem]'>
                Execute
                <Wand2 className='w-4 h-4 ml-2'/>
              </Button>
            </div>
          </form>
        </aside>
      </main>
    </div>
  )
}

